###############
POST http://localhost:3003/rsi/getRSIForSymbols
Content-Type: application/json
SAD
{
  "symbols": ["BTCUSDT", "ETHUSDT",
   "XRPUSDT","DOGEUSDT","ENAUSDT",
   "LINKUSDT","1000PEPEUSDT",
   "SUIUSDT","ADAUSDT","AVAXUSDT",
   "LTCUSDT","DOTUSDT","HBARUSDT",
   "SHIB1000USDT","ZEUSUSDT",
   "UNIUSDT","NEARUSDT","PNUTUSDT",
   "LDOUSDT","SANDUSDT","BNBUSDT",
   "XLMUSDT","COWUSDT","KAIAUSDT",
   "BCHUSDT","TRXUSDT","ETCUSDT",
   "INJUSDT","TAOUSDT","KASUSDT",
   "FTMUSDT","ONDOUSDT","AAVEUSDT",
   "GOATUSDT","UXLINKUSDT",
   "1000FLOKIUSDT",
   "CRVUSDT",
   "1000BONKUSDT",
   "GRASSUSDT",
   "ARBUSDT",
   "SEIUSDT",
   "EIGENUSDT",
   "ZROUSDT",
   "XVGUSDT",
   "WIFUSDT",
   "VIRTUALUSDT","ENSUSDT",
   "POPCATUSDT",
   "GALAUSDT",
   "WLDUSDT",
   "CHILLGUYUSDT",
   "STXUSDT","MOVEUSDT",
   "ORDIUSDT"
   ],
  "period": 120,
  "interval": 360
}

